name: Moto125 Strapi Backend — Docker Release

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: prod

    env:
      IMAGE_NAME: qadraxdev/moto125-strapi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=ref,event=tag
          labels: |
            org.opencontainers.image.title=Moto125 Strapi
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.version=${{ github.event.release.tag_name }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: backend/moto125-strapi
          file: backend/moto125-strapi/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save released image as tar.gz
        run: |
          TAG="${{ github.event.release.tag_name }}"
          docker pull "${{ env.IMAGE_NAME }}:${TAG}"
          docker save "${{ env.IMAGE_NAME }}:${TAG}" | gzip > "moto125-strapi-${TAG}.tar.gz"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: moto125-strapi-${{ github.event.release.tag_name }}.tar.gz
