name: Moto125 Monorepo — Strapi CI

on:
  push:
    branches: [main]
    paths:
      - "apps/moto125-strapi/**"
      - "packages/**"
      - "package.json"
      - "package-lock.json"
      - "lerna.json"
      - ".github/workflows/strapi-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "apps/moto125-strapi/**"
      - "packages/**"
      - "package.json"
      - "package-lock.json"
      - "lerna.json"
      - ".github/workflows/strapi-ci.yml"

permissions:
  contents: read

concurrency:
  group: strapi-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Strapi (Node 20)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install (root workspaces)
        run: npm ci

      - name: Build Strapi workspace
        run: npm run -w @moto125/strapi build
