name: Moto125 Strapi Backend — CI

on:
  push:
    branches: [main]
    paths:
      - "backend/moto125-strapi/**"
      - ".github/workflows/strapi-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "backend/moto125-strapi/**"
      - ".github/workflows/strapi-ci.yml"

permissions:
  contents: read

jobs:
  build:
    name: Build Strapi (Node 20)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/moto125-strapi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/moto125-strapi/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
